import turtle

turtle.speed(20)
turtle.pencolor("yellow")
turtle.color("yellow")
turtle.begin_fill()
turtle.circle(200)
turtle.end_fill()
turtle.penup()
turtle.goto(100,100)
turtle.pencolor("black")
turtle.pendown()
turtle.back(200)
turtle.penup()
turtle.goto(0,200)
turtle.pendown()
turtle.right(60)
turtle.forward(75)
turtle.right(130)
turtle.forward(50)
turtle.penup()
turtle.goto(100,250)
turtle.left(280)

turtle.exitonclick()
